name: CreateRelease

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushing
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'M0RMarkers'

      - name: Zip release
        run: 7z a M0RMarkers.zip * -xr!*.git*


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: M0RMarkers.zip
          token: ${{ secrets.TOKEN_GITHUB }}